/*
 * getCommand(command, callback)
 * 
 * pass a Bash command to getCommand, and receive
 * the main parts of the relevant man page!
 *
 * © 2017 Team Pengo
 *
 * Authors: Khyati Kulshreshtha,
 *          Monyett Tanzillo,
 *          Claudio Gentile,
 *          Peter Martinson 
*/


const request   = require('request'),
      cheerio   = require('cheerio'),
      striptags = require('striptags'),
      base_url  = 'http://man.he.net/man1/';

// get the command text from the URL
var fetchCommand = function(command, callback) {
  var main_url = base_url + command;
  request(main_url, function(error, response, html) {
    if (error) callback(error);
    var $ = cheerio.load(html);
    callback(null, $('pre').html());
  });
}

module.exports = function(command, callback) {
  fetchCommand(command, function(error, man) {
    if (error) callback(error);
    if ( !man ) {
      callback('Command not found!');
    }
    else {
      var command_array = man.split('\n'),
          toc          = [],
          sections     = [];

      // create TOC numbers
      command_array.forEach(function(element, index) {
        if ( /^[A-Z]/.test(element) ) {
          toc.push(index);
        }
      });

      // create TOC section labels
      toc.forEach(function(element) {
        sections.push(command_array[element]);
      });

      function createSection(title) {
        var section_index      = toc[sections.indexOf(title.toUpperCase())],
            next_section_index = toc[sections.indexOf(title.toUpperCase())+1],
            long_section_flag  = 0,
            section;
        if ( next_section_index - section_index >= 20 ) {
          next_section_index = section_index + 20;
          long_section_flag = 1;
        }
        section = command_array.filter(function(element, index) {
          if ( index > section_index && index < next_section_index ) {
            return element;
          }
        }).join('\n');
        if ( long_section_flag ) {
          section += '\r\r        _...section clipped! See ' + base_url + command + ' for complete text._';
        }
        return striptags(section.replace(/&apos;/g, "'"));
      }

      callback(null, {
        syntax      : createSection('synopsis'),
        description : createSection('description'),
        options     : createSection('options'),
        examples    : createSection('examples'),
        source_href : base_url + command
      });
    }
  });
}


var all_commands = ['2to3', '2to3-2', '411toppm', 'a2p', 'ab', 'aclocal',
  'aclocal-1', 'aconnect', 'acpi_available', 'acyclic', 'add-patch',
  'addr2line', 'alpine', 'alpinef', 'alsactl', 'alsaloop', 'alsamixer',
  'amidi', 'amixer', 'animate', 'annotate-output', 'anytopnm', 'aplay',
  'aplaymidi', 'apm_available', 'appres', 'apr-1-config', 'apr-config',
  'apropos', 'apt-extracttemplates', 'apt-ftparchive', 'apt-sortpkgs',
  'aptitude-create-state-bundle', 'aptitude-run-state-bundle', 'apxs2', 'ar',
  'arch', 'archpath', 'arecord', 'arecordmidi', 'as', 'asciitopgm', 'aseqdump',
  'aseqnet', 'asn1parse', 'aspell', 'aspell-import', 'at', 'atktopbm', 'atq',
  'atrm', 'autoconf', 'autoheader', 'autom4te', 'automake', 'automake-1',
  'autoreconf', 'autoscan', 'autoupdate', 'awk', 'axi-cache', 'b2m', 'base64',
  'basename', 'bash', 'bashbug', 'batch', 'bcomps', 'bdftopcf', 'bdftruncate',
  'bioradtopgm', 'bison', 'bmptopnm', 'bmptoppm', 'bonobo-activation-server',
  'brushtopbm', 'bsd-csh', 'bsd-from', 'bsd-mailx', 'bsd-write', 'bts',
  'build-rdeps', 'buildhash', 'bunzip2', 'busybox', 'byobu', 'byobu-config',
  'byobu-ctrl-a', 'byobu-disable', 'byobu-enable', 'byobu-export',
  'byobu-janitor', 'byobu-launch', 'byobu-launcher', 'byobu-launcher-install',
  'byobu-launcher-uninstall', 'byobu-layout', 'byobu-quiet',
  'byobu-reconnect-sockets', 'byobu-screen', 'byobu-select-backend',
  'byobu-select-profile', 'byobu-select-session', 'byobu-shell',
  'byobu-silent', 'byobu-status', 'byobu-status-detail', 'byobu-tmux', 'bzcat',
  'bzcmp', 'bzdiff', 'bzegrep', 'bzexe', 'bzfgrep', 'bzgrep', 'bzip2',
  'bzip2recover', 'bzless', 'bzmore', 'c++', 'c++filt', 'c2ph', 'c89',
  'c89-gcc', 'c99', 'c99-gcc', 'c_rehash', 'ca', 'cadaver', 'cal', 'calendar',
  'captoinfo', 'cat', 'catalyst', 'catchsegv', 'cc', 'ccmakedep', 'ccomps',
  'chage', 'changestool', 'chardet', 'chartex', 'chattr', 'chcon', 'chdist',
  'check-bios-nx', 'check-language-support', 'checkbashisms', 'checkisomd5',
  'chfn', 'chgrp', 'chkdupexe', 'chklastlog', 'chkrootkit', 'chkwtmp', 'chmod',
  'chown', 'chrt', 'chsh', 'chvt', 'ci', 'cifsiostat', 'ciphers', 'circo',
  'ckbcomp', 'cksum', 'cleanlinks', 'clear', 'clear_console', 'cmew', 'cmp',
  'cms', 'cmuwmtopbm', 'co', 'codepage', 'col', 'colcrt', 'colrm', 'column',
  'combinediff', 'comm', 'compare', 'compile_et', 'compose', 'composite',
  'config', 'config_data', 'conjure', 'convert', 'corelist', 'cowpoke', 'cp',
  'cpan', 'cpan2dist', 'cpanp', 'cpansign', 'cpio', 'cpp', 'cpp-4', 'crc32',
  'crl', 'crl2pkcs7', 'crontab', 'csh', 'csplit', 'ctags', 'curl', 'cut',
  'cvs', 'cvs-debc', 'cvs-debi', 'cvs-debrelease', 'cvs-debuild',
  'cvs-switchroot', 'dash', 'date', 'dbconfig-generate-include',
  'dbconfig-load-include', 'dbench', 'dbicadmin', 'dbicdump', 'dbilogstrip',
  'dbiprof', 'dbiproxy', 'dbmmanage', 'dbus-cleanup-sockets', 'dbus-daemon',
  'dbus-launch', 'dbus-monitor', 'dbus-send', 'dbus-uuidgen', 'dch', 'dcmd',
  'dcontrol', 'dcut', 'dd', 'dd-list', 'deallocvt', 'deb-reversion', 'debc',
  'debchange', 'debcheckout', 'debclean', 'debcommit', 'debconf',
  'debconf-apt-progress', 'debconf-communicate', 'debconf-copydb',
  'debconf-escape', 'debconf-gettextize', 'debconf-set-selections',
  'debconf-show', 'debconf-updatepo', 'debdiff', 'debi', 'debpkg',
  'debrelease', 'debrsign', 'debsign', 'debsnap', 'debuild', 'defmt-c',
  'defmt-sh', 'defoma', 'defoma-app', 'defoma-font', 'defoma-hints',
  'defoma-id', 'defoma-psfont-installer', 'defoma-subst', 'defoma-user',
  'dehtmldiff', 'deliver', 'dep3changelog', 'desktop2menu', 'devscripts', 'df',
  'dget', 'dgst', 'dh', 'dh_apparmor', 'dh_auto_build', 'dh_auto_clean',
  'dh_auto_configure', 'dh_auto_install', 'dh_auto_test',
  'dh_autotools-dev_restoreconfig', 'dh_autotools-dev_updateconfig',
  'dh_bash-completion', 'dh_bugfiles', 'dh_builddeb', 'dh_clean',
  'dh_compress', 'dh_desktop', 'dh_dpatch_patch', 'dh_dpatch_unpatch',
  'dh_fixperms', 'dh_gconf', 'dh_gencontrol', 'dh_icons', 'dh_install',
  'dh_installcatalogs', 'dh_installchangelogs', 'dh_installcron',
  'dh_installdeb', 'dh_installdebconf', 'dh_installdefoma', 'dh_installdirs',
  'dh_installdocs', 'dh_installemacsen', 'dh_installexamples',
  'dh_installgsettings', 'dh_installifupdown', 'dh_installinfo',
  'dh_installinit', 'dh_installlogcheck', 'dh_installlogrotate',
  'dh_installman', 'dh_installmanpages', 'dh_installmenu', 'dh_installmime',
  'dh_installmodules', 'dh_installpam', 'dh_installppp', 'dh_installtex',
  'dh_installudev', 'dh_installwm', 'dh_installxfonts',
  'dh_installxmlcatalogs', 'dh_link', 'dh_lintian', 'dh_listpackages',
  'dh_makeshlibs', 'dh_md5sums', 'dh_movefiles', 'dh_perl', 'dh_perl_dbi',
  'dh_prep', 'dh_pycentral', 'dh_pysupport', 'dh_python', 'dh_python2',
  'dh_scrollkeeper', 'dh_shlibdeps', 'dh_strip', 'dh_suidregister',
  'dh_testdir', 'dh_testroot', 'dh_ucf', 'dh_undocumented', 'dh_usrlocal',
  'dhparam', 'dialog', 'diff', 'diff2patches', 'diff3', 'diffimg', 'diffstat',
  'dig', 'dijkstra', 'dir', 'dircolors', 'dirname', 'diskd', 'diskseekd',
  'display', 'dlltool', 'dmesg', 'dnsdomainname', 'docbook-to-man',
  'domainname', 'dot', 'dot2gxl', 'dotlockfile', 'dotty', 'doveadm',
  'doveadm-altmove', 'doveadm-auth', 'doveadm-config', 'doveadm-director',
  'doveadm-dump', 'doveadm-expunge', 'doveadm-fetch', 'doveadm-force-resync',
  'doveadm-help', 'doveadm-import', 'doveadm-index', 'doveadm-kick',
  'doveadm-log', 'doveadm-mailbox', 'doveadm-move', 'doveadm-penalty',
  'doveadm-purge', 'doveadm-pw', 'doveadm-quota', 'doveadm-reload',
  'doveadm-search', 'doveadm-stop', 'doveadm-user', 'doveadm-who', 'doveconf',
  'dovecot', 'dovecot-lda', 'dpatch', 'dpatch-convert-diffgz',
  'dpatch-edit-patch', 'dpatch-list-patch', 'dpkg', 'dpkg-architecture',
  'dpkg-buildflags', 'dpkg-buildpackage', 'dpkg-checkbuilddeps', 'dpkg-deb',
  'dpkg-depcheck', 'dpkg-distaddfile', 'dpkg-genbuilddeps', 'dpkg-genchanges',
  'dpkg-gencontrol', 'dpkg-gensymbols', 'dpkg-maintscript-helper',
  'dpkg-mergechangelogs', 'dpkg-name', 'dpkg-parsechangelog', 'dpkg-query',
  'dpkg-scanpackages', 'dpkg-scansources', 'dpkg-shlibdeps', 'dpkg-source',
  'dpkg-split', 'dpkg-trigger', 'dpkg-vendor', 'dprofpp', 'dput', 'dsa',
  'dsaparam', 'dscextract', 'dscverify', 'dselect', 'dsync', 'du', 'dumpelf',
  'dumpkeys', 'dvipdf', 'ebrowse', 'ec', 'echo', 'ecparam',
  'ecryptfs-add-passphrase', 'ecryptfs-generate-tpm-key',
  'ecryptfs-insert-wrapped-passphrase-into-keyring', 'ecryptfs-mount-private',
  'ecryptfs-recover-private', 'ecryptfs-rewrap-passphrase',
  'ecryptfs-rewrite-file', 'ecryptfs-setup-private', 'ecryptfs-setup-swap',
  'ecryptfs-stat', 'ecryptfs-umount-private', 'ecryptfs-unwrap-passphrase',
  'ecryptfs-wrap-passphrase', 'ed', 'edit', 'edit-patch', 'editdiff', 'editor',
  'editres', 'egrep', 'eject', 'elfedit', 'emacs', 'emacs23', 'emacs23-x',
  'emacsclient', 'enc', 'enc2xs', 'env', 'envsubst', 'eps2eps', 'eqn', 'erb',
  'erb1', 'errstr', 'estcall', 'estcmd', 'estfxasis', 'estfxfilter',
  'estfxmantotxt', 'estfxmsotohtml', 'estfxpdftohtml', 'estload', 'estmaster',
  'estwaver', 'estwolefind', 'etags', 'eview', 'evim', 'ex', 'expand',
  'expiry', 'expr', 'eyuvtoppm', 'factor', 'fail2ban-client', 'fail2ban-regex',
  'fail2ban-server', 'faked', 'faked-sysv', 'faked-tcp', 'fakeroot',
  'fakeroot-sysv', 'fakeroot-tcp', 'fallocate', 'false', 'fc-cache', 'fc-cat',
  'fc-list', 'fc-match', 'fc-query', 'fc-scan', 'fdlist', 'fdmount',
  'fdmountd', 'fdp', 'fdrawcmd', 'fdumount', 'fgconsole', 'fgrep',
  'fiascotopnm', 'file', 'filterdiff', 'find', 'find2perl', 'findaffix',
  'findrule', 'fitstopnm', 'fixcvsdiff', 'flipdiff', 'flock', 'floppycontrol',
  'floppymeter', 'fmt', 'fold', 'font2c', 'fonttosfnt', 'formail',
  'format-sql', 'free', 'fribidi', 'from', 'fslsfonts', 'fstobdf', 'fstopgm',
  'ftp', 'funzip', 'fuser', 'fusermount', 'g++', 'g++-4', 'g3topbm', 'gawk',
  'gc', 'gcc', 'gcc-4', 'gccmakedep', 'gconftool', 'gconftool-2', 'gcov',
  'gcov-4', 'gemtopbm', 'gemtopnm', 'gencat', 'gendsa', 'genpkey', 'genrsa',
  'geqn', 'getbuildlog', 'getconf', 'getent', 'getfdprm', 'getopt', 'gettext',
  'gettextize', 'ghostscript', 'giftopnm', 'ginstall-info', 'gml2gv',
  'gnome-keyring-daemon', 'gold', 'gouldtoppm', 'gpasswd', 'gpg', 'gpg-zip',
  'gpgsplit', 'gpgv', 'gpic', 'gprof', 'grep', 'grep-aptavail',
  'grep-available', 'grep-changelog', 'grep-dctrl', 'grep-debtags',
  'grep-excuses', 'grep-status', 'grepdiff', 'groff', 'grog', 'grops',
  'grotty', 'groups', 'grub-bin2h', 'grub-editenv', 'grub-fstest',
  'grub-menulst2cfg', 'grub-mkfont', 'grub-mkimage', 'grub-mklayout',
  'grub-mkpasswd-pbkdf2', 'grub-mkrelpath', 'grub-mkrescue', 'grub-mount',
  'grub-script-check', 'gs', 'gsbj', 'gsdj', 'gsdj500',
  'gsettings-data-convert', 'gsettings-schema-convert', 'gslj', 'gslp', 'gsnd',
  'gtbl', 'gtk-query-immodules-2', 'gtk-query-immodules-3',
  'gtk-update-icon-cache', 'gtk-update-icon-cache-3', 'gunzip', 'gv2gxl',
  'gvcolor', 'gvgen', 'gview', 'gvim', 'gvimdiff', 'gvimtutor', 'gvpack',
  'gvpr', 'gxl2dot', 'gxl2gv', 'gzexe', 'gzip', 'h2ph', 'h2xs', 'hd', 'head',
  'helpztags', 'hexdump', 'hipstopgm', 'host', 'hostid', 'hostname', 'htdbm',
  'htdigest', 'html2text', 'html_formfu_deploy', 'html_formfu_dumpconf',
  'htop', 'htpasswd', 'httxt2dbm', 'iceauth', 'icombine', 'icontopbm', 'iconv',
  'id', 'ident', 'identify', 'iecset', 'ifnames', 'igawk', 'ijoin',
  'ilbmtoppm', 'imake', 'imgsize', 'imgtoppm', 'implantisomd5', 'import',
  'incm', 'info', 'infobrowser', 'infocmp', 'infokey', 'infotocap',
  'innochecksum', 'innotop', 'inputattach', 'install', 'install-info',
  'instant', 'instmodsh', 'interdiff', 'intro', 'ionice', 'iostat', 'ipcmk',
  'ipcrm', 'ipcs', 'iproxy', 'ipv4calc', 'irb', 'irb1', 'irqbalance',
  'ischroot', 'ispell', 'ispell-wrapper', 'join', 'join-dctrl', 'jpegtopnm',
  'json_pp', 'json_xs', 'kbd_mode', 'keyctl', 'kill', 'killall', 'koi8rxterm',
  'krb5-config', 'kvm-ok', 'l4p-tmpl', 'last', 'lastb', 'lcf', 'ld', 'ldd',
  'leaftoppm', 'lefty', 'less', 'lessecho', 'lessfile', 'lesskey', 'lesspipe',
  'lexgrog', 'libnetcfg', 'libtool', 'libtoolize', 'licensecheck', 'link',
  'links', 'lintian', 'lintian-info', 'linux32', 'linux64', 'lispmtopgm',
  'list-unreleased', 'listres', 'ln', 'lndir', 'lneato', 'loadkeys', 'locale',
  'localedef', 'lockfile', 'lockfile-check', 'lockfile-create',
  'lockfile-progs', 'lockfile-remove', 'lockfile-touch', 'logger', 'login',
  'logname', 'logresolve', 'look', 'lorder', 'ls', 'lsattr', 'lsb_release',
  'lscpu', 'lsdiff', 'lshw', 'lspgpot', 'ltrace', 'luit', 'lwp-download',
  'lwp-dump', 'lwp-mirror', 'lwp-request', 'lxterm', 'lynx', 'lz', 'lzcat',
  'lzcmp', 'lzdiff', 'lzegrep', 'lzfgrep', 'lzgrep', 'lzless', 'lzma',
  'lzmainfo', 'lzmore', 'm4', 'macptopbm', 'mail', 'mail-lock',
  'mail-touchlock', 'mail-unlock', 'maildirmake', 'mailstat', 'mailx', 'make',
  'make-kpkg', 'make_method', 'makedepend', 'makeg', 'makeinfo', 'man',
  'manconv', 'manpage-alert', 'manpath', 'mass-bug', 'mattrib', 'mawk',
  'mbadblocks', 'mcat', 'mcd', 'mcheck', 'mcomp', 'mcookie', 'mcopy', 'mcpp',
  'md2', 'md4', 'md5', 'md5sum', 'mdatopbm', 'mdc2', 'mdel', 'mdeltree',
  'mdiff', 'mdir', 'mdu', 'mech-dump', 'memcached', 'merge', 'mergechanges',
  'mergelib', 'mesg', 'mew-pinentry', 'mewcat', 'mewdecode', 'mewencode',
  'mewest', 'mewl', 'mewstunnel', 'mformat', 'mgrtopbm', 'minfo',
  'mk-build-deps', 'mkdir', 'mkdirhier', 'mkfifo', 'mkfontdir', 'mkfontscale',
  'mkhtmlindex', 'mkmanifest', 'mknod', 'mkpasswd', 'mktemp', 'mlabel',
  'mlock', 'mm2gv', 'mmd', 'mmount', 'mmove', 'mogrify', 'montage', 'more',
  'mount', 'mountpoint', 'mpartition', 'mpstat', 'mrd', 'mren', 'msgattrib',
  'msgcat', 'msgcmp', 'msgcomm', 'msgconv', 'msgen', 'msgexec', 'msgfilter',
  'msgfmt', 'msggrep', 'msginit', 'msgmerge', 'msgunfmt', 'msguniq',
  'mshowfat', 'msql2mysql', 'mt', 'mt-gnu', 'mtools', 'mtoolstest', 'mtrace',
  'mtvtoppm', 'mtype', 'munchlist', 'munin-node', 'munin-node-configure',
  'munin-run', 'munindoc', 'mv', 'mxtar', 'my_print_defaults', 'myisam_ftdump',
  'myisamchk', 'myisamlog', 'myisampack', 'mysql', 'mysql_client_test',
  'mysql_client_test_embedded', 'mysql_config', 'mysql_convert_table_format',
  'mysql_find_rows', 'mysql_fix_extensions', 'mysql_install_db',
  'mysql_plugin', 'mysql_secure_installation', 'mysql_setpermission',
  'mysql_tableinfo', 'mysql_tzinfo_to_sql', 'mysql_upgrade', 'mysql_waitpid',
  'mysql_zap', 'mysqlaccess', 'mysqladmin', 'mysqlanalyze', 'mysqlbinlog',
  'mysqlbug', 'mysqlcheck', 'mysqld_multi', 'mysqld_safe', 'mysqldump',
  'mysqldumpslow', 'mysqlhotcopy', 'mysqlimport', 'mysqlman', 'mysqloptimize',
  'mysqlrepair', 'mysqlreport', 'mysqlshow', 'mysqlslap', 'mysqltest',
  'mysqltest_embedded', 'mzip', 'namecheck', 'namei', 'nano', 'nawk', 'nc',
  'nc_openbsd', 'ncal', 'ncurses5-config', 'ncursesw5-config', 'neato',
  'neotoppm', 'neqn', 'net-snmp-config', 'netcat', 'netkit-ftp', 'netkit-rcp',
  'netkit-rlogin', 'netkit-rsh', 'netpbm', 'newgrp', 'nfsiostat', 'ngettext',
  'nice', 'nisdomainname', 'nl', 'nlmconv', 'nm', 'nmudiff', 'nohup', 'nop',
  'nproc', 'nroff', 'nseq', 'nsgmls', 'nslookup', 'nsupdate',
  'obex-data-server', 'objcopy', 'objdump', 'ocsp', 'od', 'ods-server',
  'oldfind', 'omshell', 'on_ac_power', 'open', 'openssl', 'openvt', 'osage',
  'pager', 'palmtopnm', 'pamcut', 'pamdeinterlace', 'pamdice', 'pamfile',
  'pamoil', 'pamstack', 'pamstretch', 'pamstretch-gen', 'paperconf',
  'parsechangelog', 'passwd', 'paste', 'patch', 'pathchk', 'pax', 'paxcpio',
  'paxctl', 'paxtar', 'pbmclean', 'pbmfilters', 'pbmlife', 'pbmmake',
  'pbmmask', 'pbmpage', 'pbmpscale', 'pbmreduce', 'pbmtext', 'pbmtextps',
  'pbmto10x', 'pbmtoascii', 'pbmtoatk', 'pbmtobbnbg', 'pbmtocmuwm',
  'pbmtoepsi', 'pbmtoepson', 'pbmtog3', 'pbmtogem', 'pbmtogo', 'pbmtoicon',
  'pbmtolj', 'pbmtomacp', 'pbmtomda', 'pbmtomgr', 'pbmtonokia', 'pbmtopgm',
  'pbmtopi3', 'pbmtoplot', 'pbmtoppa', 'pbmtopsg3', 'pbmtoptx', 'pbmtowbmp',
  'pbmtox10bm', 'pbmtoxbm', 'pbmtoybm', 'pbmtozinc', 'pbmupc', 'pcre-config',
  'pcxtoppm', 'pdb', 'pdb2', 'pdf2dsc', 'pdf2ps', 'pdffonts', 'pdfimages',
  'pdfinfo', 'pdfopt', 'pdftexi2dvi', 'pdftoppm', 'pdftops', 'pdftotext',
  'pdns_recursor', 'peekfd', 'perl', 'perl5', 'perl5004delta', 'perl5005delta',
  'perl5100delta', 'perl5101delta', 'perl5110delta', 'perl5111delta',
  'perl5112delta', 'perl5113delta', 'perl5114delta', 'perl5115delta',
  'perl5120delta', 'perl5121delta', 'perl5122delta', 'perl5123delta',
  'perl5130delta', 'perl51310delta', 'perl51311delta', 'perl5131delta',
  'perl5132delta', 'perl5133delta', 'perl5134delta', 'perl5135delta',
  'perl5136delta', 'perl5137delta', 'perl5138delta', 'perl5139delta',
  'perl5140delta', 'perl5141delta', 'perl5142delta', 'perl561delta',
  'perl56delta', 'perl570delta', 'perl571delta', 'perl572delta',
  'perl573delta', 'perl581delta', 'perl582delta', 'perl583delta',
  'perl584delta', 'perl585delta', 'perl586delta', 'perl587delta',
  'perl588delta', 'perl589delta', 'perl58delta', 'perl590delta',
  'perl591delta', 'perl592delta', 'perl593delta', 'perl594delta',
  'perl595delta', 'perlaix', 'perlamiga', 'perlapi', 'perlapio',
  'perlartistic', 'perlbeos', 'perlbook', 'perlboot', 'perlbot', 'perlbs2000',
  'perlbug', 'perlcall', 'perlce', 'perlcheat', 'perlclib', 'perlcn',
  'perlcommunity', 'perlcompile', 'perlcygwin', 'perldata', 'perldbmfilter',
  'perldebguts', 'perldebtut', 'perldebug', 'perldelta', 'perldgux',
  'perldiag', 'perldoc', 'perldos', 'perldsc', 'perlebcdic', 'perlembed',
  'perlepoc', 'perlfaq', 'perlfaq1', 'perlfaq2', 'perlfaq3', 'perlfaq4',
  'perlfaq5', 'perlfaq6', 'perlfaq7', 'perlfaq8', 'perlfaq9', 'perlfilter',
  'perlfork', 'perlform', 'perlfreebsd', 'perlfunc', 'perlgit', 'perlglossary',
  'perlgpl', 'perlguts', 'perlhack', 'perlhacktips', 'perlhacktut',
  'perlhaiku', 'perlhist', 'perlhpux', 'perlhurd', 'perlintern', 'perlinterp',
  'perlintro', 'perliol', 'perlipc', 'perlirix', 'perlivp', 'perljp', 'perlko',
  'perllexwarn', 'perllinux', 'perllocale', 'perllol', 'perlmacos',
  'perlmacosx', 'perlmod', 'perlmodinstall', 'perlmodlib', 'perlmodstyle',
  'perlmpeix', 'perlmroapi', 'perlnetware', 'perlnewmod', 'perlnumber',
  'perlobj', 'perlop', 'perlopenbsd', 'perlopentut', 'perlos2', 'perlos390',
  'perlos400', 'perlpacktut', 'perlperf', 'perlplan9', 'perlpod',
  'perlpodspec', 'perlpodstyle', 'perlpolicy', 'perlport', 'perlpragma',
  'perlqnx', 'perlre', 'perlreapi', 'perlrebackslash', 'perlrecharclass',
  'perlref', 'perlreftut', 'perlreguts', 'perlrequick', 'perlreref',
  'perlretut', 'perlriscos', 'perlrun', 'perlsec', 'perlsolaris', 'perlsource',
  'perlstyle', 'perlsub', 'perlsymbian', 'perlsyn', 'perlthanks', 'perlthrtut',
  'perltie', 'perltoc', 'perltodo', 'perltooc', 'perltoot', 'perltrap',
  'perltru64', 'perltw', 'perlunicode', 'perlunifaq', 'perluniintro',
  'perluniprops', 'perlunitut', 'perlutil', 'perluts', 'perlvar', 'perlvmesa',
  'perlvms', 'perlvos', 'perlwin32', 'perlxs', 'perlxstut', 'perror', 'pf2afm',
  'pfbtopfa', 'pftp', 'pg', 'pg_config', 'pgawk', 'pgmbentley', 'pgmcrater',
  'pgmedge', 'pgmenhance', 'pgmhist', 'pgmkernel', 'pgmnoise', 'pgmnorm',
  'pgmoil', 'pgmramp', 'pgmslice', 'pgmtexture', 'pgmtofs', 'pgmtolispm',
  'pgmtopbm', 'pgmtoppm', 'pgrep', 'php', 'php-config', 'php-config5', 'php5',
  'phpize', 'phpize5', 'pi1toppm', 'pi3topbm', 'pic', 'pico', 'piconv',
  'pidstat', 'pinentry', 'pinky', 'pjtoppm', 'pkcs12', 'pkcs7', 'pkcs8',
  'pkey', 'pkeyparam', 'pkeyutl', 'pkg-config', 'pkill', 'pl2pm', 'plackup',
  'pldd', 'plog', 'plotchangelog', 'pmap', 'pngtopnm', 'pnmalias', 'pnmarith',
  'pnmcat', 'pnmcolormap', 'pnmcomp', 'pnmconvol', 'pnmcrop', 'pnmcut',
  'pnmdepth', 'pnmenlarge', 'pnmfile', 'pnmflip', 'pnmgamma', 'pnmhisteq',
  'pnmhistmap', 'pnmindex', 'pnminterp', 'pnminterp-gen', 'pnminvert',
  'pnmmargin', 'pnmmontage', 'pnmnlfilt', 'pnmnoraw', 'pnmnorm', 'pnmpad',
  'pnmpaste', 'pnmpsnr', 'pnmquant', 'pnmremap', 'pnmrotate', 'pnmscale',
  'pnmscalefixed', 'pnmshear', 'pnmsmooth', 'pnmsplit', 'pnmtile', 'pnmtoddif',
  'pnmtofiasco', 'pnmtofits', 'pnmtojpeg', 'pnmtopalm', 'pnmtoplainpnm',
  'pnmtopng', 'pnmtops', 'pnmtorast', 'pnmtorle', 'pnmtosgi', 'pnmtosir',
  'pnmtotiff', 'pnmtotiffcmyk', 'pnmtoxwd', 'po2debconf', 'pod2html',
  'pod2latex', 'pod2man', 'pod2readme', 'pod2text', 'pod2usage', 'podchecker',
  'podebconf-display-po', 'podebconf-report-po', 'podselect', 'poff', 'pon',
  'ppm3d', 'ppmbrighten', 'ppmchange', 'ppmcie', 'ppmcolormask', 'ppmcolors',
  'ppmdim', 'ppmdist', 'ppmdither', 'ppmfade', 'ppmflash', 'ppmforge',
  'ppmhist', 'ppmlabel', 'ppmmake', 'ppmmix', 'ppmnorm', 'ppmntsc', 'ppmpat',
  'ppmquant', 'ppmquantall', 'ppmqvga', 'ppmrainbow', 'ppmrelief', 'ppmshadow',
  'ppmshift', 'ppmspread', 'ppmtoacad', 'ppmtobmp', 'ppmtoeyuv', 'ppmtogif',
  'ppmtoicr', 'ppmtoilbm', 'ppmtojpeg', 'ppmtoleaf', 'ppmtolj', 'ppmtomap',
  'ppmtomitsu', 'ppmtompeg', 'ppmtoneo', 'ppmtopcx', 'ppmtopgm', 'ppmtopi1',
  'ppmtopict', 'ppmtopj', 'ppmtopuzz', 'ppmtorgb3', 'ppmtosixel', 'ppmtotga',
  'ppmtouil', 'ppmtowinicon', 'ppmtoxpm', 'ppmtoyuv', 'ppmtoyuvsplit', 'ppmtv',
  'ppthtml', 'pr', 'precat', 'preconv', 'prename', 'preunzip', 'prezip',
  'prezip-bin', 'print', 'printafm', 'printenv', 'printerbanner', 'printf',
  'proclint', 'procmail', 'prove', 'prtstat', 'prune', 'ps', 'ps2ascii',
  'ps2epsi', 'ps2pdf', 'ps2pdf12', 'ps2pdf13', 'ps2pdf14', 'ps2pdfwr', 'ps2ps',
  'psed', 'psfaddtable', 'psfgettable', 'psfstriptable', 'psfxtable',
  'psidtopgm', 'pspax', 'pstopnm', 'pstree', 'pstruct', 'ptar', 'ptardiff',
  'ptargrep', 'pts-subscribe', 'pts-unsubscribe', 'ptx', 'pwd', 'pwdx',
  'py_compilefiles', 'pycentral', 'pyclean', 'pycompile', 'pydoc', 'pydoc2',
  'pygettext', 'pygettext2', 'python', 'python2', 'pyversions', 'qrttoppm',
  'rand', 'ranlib', 'rasttopnm', 'rawtopgm', 'rawtoppm', 'rbash', 'rc-alert',
  'rcp', 'rcs', 'rcs-checkin', 'rcsclean', 'rcsdiff', 'rcsfreeze', 'rcsintro',
  'rcsmerge', 'rdmsr', 'rdoc', 'rdoc1', 're2c', 'readelf', 'readlink',
  'readprofile', 'rec_control', 'recode-sr-latin', 'recountdiff', 'red',
  'rediff', 'regexp-assemble', 'rename', 'renice', 'replace', 'report-hw',
  'reprepro', 'req', 'reset', 'resize', 'resolve_stack_dump', 'resolveip',
  'rev', 'revpath', 'rgb3toppm', 'rgrep', 'rgview', 'rgvim', 'ri', 'ri1',
  'ripemd160', 'rletopnm', 'rlog', 'rlogin', 'rm', 'rmadison', 'rmdir',
  'rnano', 'rngtest', 'rpcgen', 'rpdump', 'rpload', 'rredtool', 'rsa',
  'rsautl', 'rsh', 'rssh', 'rstart', 'rstartd', 'rsync', 'ruby', 'ruby1',
  'run-mailcap', 'run-with-aspell', 'runcon', 'rview', 'rvim', 's2p',
  's_client', 's_server', 's_time', 'sa-awl', 'sa-check_spamd', 'sa-compile',
  'sa-learn', 'sa-update', 'sadf', 'sar', 'sbigtopgm', 'scandeps', 'scanelf',
  'scanerrlog', 'scanmacho', 'sccmap', 'scp', 'screen', 'screendump', 'script',
  'scriptreplay', 'sdiff', 'sed', 'see', 'select-default-iwrap',
  'select-editor', 'sensible-browser', 'sensible-editor', 'sensible-pager',
  'sensors', 'sensors-conf-convert', 'seq', 'sess_id', 'sessreg', 'setfdprm',
  'setleds', 'setmetamode', 'setsid', 'setterm', 'setupcon', 'sfdp', 'sftp',
  'sg', 'sgitopnm', 'sgml2xml', 'sgmlnorm', 'sh', 'sha', 'sha1', 'sha1sum',
  'sha224sum', 'sha256sum', 'sha384sum', 'sha512sum', 'shar', 'shasum',
  'showfont', 'showkey', 'showrgb', 'shred', 'shtool', 'shtool-arx',
  'shtool-echo', 'shtool-fixperm', 'shtool-install', 'shtool-mdate',
  'shtool-mkdir', 'shtool-mkln', 'shtool-mkshadow', 'shtool-move',
  'shtool-path', 'shtool-platform', 'shtool-prop', 'shtool-rotate',
  'shtool-scpp', 'shtool-slo', 'shtool-subst', 'shtool-table',
  'shtool-tarball', 'shtool-version', 'shtoolize', 'shuf', 'sirtopnm', 'size',
  'skill', 'slabtop', 'sldtoppm', 'sleep', 'slogin', 'smew', 'smime',
  'smproxy', 'smyrna', 'snice', 'snmpkey', 'soelim', 'sort', 'sort-dctrl',
  'spam', 'spamassassin', 'spamassassin-run', 'spamc', 'spctoppm',
  'speaker-test', 'speed', 'spent', 'spfquery', 'spkac', 'splain', 'split',
  'splitdiff', 'splitfont', 'sprof', 'sputoppm', 'sq', 'sqlite3', 'sqlt',
  'sqlt-diagram', 'sqlt-diff', 'sqlt-diff-old', 'sqlt-dumper', 'sqlt-graph',
  'ssh', 'ssh-add', 'ssh-agent', 'ssh-argv0', 'ssh-copy-id', 'ssh-import-id',
  'ssh-keygen', 'ssh-keyscan', 'ssh-vulnkey', 'st4topgm', 'stat', 'stdbuf',
  'strace', 'stream', 'strings', 'strip', 'stty', 'stubmaker', 'su', 'sum',
  'superformat', 'suspicious-source', 'svn', 'svn-backup-dumps', 'svn-bisect',
  'svn-clean', 'svn-fast-backup', 'svn-hot-backup', 'svn2cl', 'svn_load_dirs',
  'svnadmin', 'svndumpfilter', 'svnlook', 'svnpath', 'svnsync', 'svnversion',
  'svnwrap', 'sync', 'tab2graph', 'tablify', 'tabmerge', 'tabs', 'tac',
  'tagpending', 'tail', 'tailf', 'tar', 'taskset', 'tbench', 'tbench_srv',
  'tbl', 'tbl-dctrl', 'tclsh', 'tclsh8', 'tee', 'telnet', 'tempfile', 'test',
  'testrb', 'testrb1', 'texi2dvi', 'texi2html', 'texi2pdf', 'texindex',
  'tgatoppm', 'tgz', 'thinkjettopbm', 'tic', 'tifftopnm', 'time', 'timelimit',
  'timeout', 'tload', 'tmux', 'toe', 'top', 'touch', 'tpage', 'tput', 'tr',
  'transition-check', 'tred', 'troff', 'true', 'truncate', 'tryaffix', 'ts',
  'tset', 'tsget', 'tsort', 'ttree', 'tty', 'twopi', 'tzselect', 'ucf', 'ucfq',
  'ucfr', 'ucs2any', 'udisks', 'udisks-tcp-bridge', 'ul', 'ulockmgr_server',
  'umount', 'uname', 'uncompress', 'unexpand', 'unflatten', 'unicode_start',
  'unicode_stop', 'unify', 'uniq', 'unlink', 'unlzma', 'unshar', 'unshare',
  'unsq', 'unwrapdiff', 'unxz', 'unzip', 'unzipsfx', 'update-fmtutil',
  'update-fontlang', 'update-language', 'update-language-dat',
  'update-language-def', 'update-mime-database', 'update-updmap', 'uptime',
  'usb-devices', 'usbmuxd', 'uscan', 'users', 'uudecode', 'uuencode',
  'uuidgen', 'uupdate', 'uxterm', 'uz', 'vacation', 'vdir', 'verify',
  'version', 'vi', 'view', 'viewres', 'vim', 'vimdiff', 'vimdot', 'vimtutor',
  'volname', 'w', 'w3m', 'w3mman', 'wall', 'watch', 'wbmptopbm', 'wc', 'wdiff',
  'wdiff2', 'webalizer', 'webazolver', 'wftopfa', 'wget', 'what-patch',
  'whatis', 'whereis', 'which', 'whiptail', 'who', 'who-uploads', 'whoami',
  'whodepends', 'windmc', 'winicontoppm', 'wish', 'wish8', 'wn', 'wnb',
  'wnintro', 'wnpp-alert', 'wnpp-check', 'word-list-compress', 'wordnet',
  'wrap-and-sort', 'write', 'wrmsr', 'www-browser', 'x-terminal-emulator',
  'x509', 'x86_64-linux-gnu-cpp', 'x86_64-linux-gnu-cpp-4',
  'x86_64-linux-gnu-g++', 'x86_64-linux-gnu-g++-4', 'x86_64-linux-gnu-gcc',
  'x86_64-linux-gnu-gcc-4', 'xargs', 'xauth', 'xbmtopbm', 'xcmsdb', 'xdfcopy',
  'xdfformat', 'xdpyinfo', 'xdriinfo', 'xev', 'xfd', 'xfontsel', 'xfsinfo',
  'xgamma', 'xgettext', 'xhost', 'ximtoppm', 'xkill', 'xlhtml', 'xlsatoms',
  'xlsclients', 'xlsfonts', 'xmessage', 'xmkmf', 'xmodmap', 'xpath',
  'xpmtoppm', 'xprop', 'xrandr', 'xrdb', 'xrefresh', 'xset', 'xsetmode',
  'xsetpointer', 'xsetroot', 'xsltproc', 'xsm', 'xstdcmap', 'xsubpp', 'xterm',
  'xvidtune', 'xvinfo', 'xvminitoppm', 'xwdtopnm', 'xwininfo', 'xxd', 'xz',
  'xzcat', 'xzcmp', 'xzdiff', 'xzegrep', 'xzfgrep', 'xzgrep', 'xzless',
  'xzmore', 'yacc', 'ybmtopbm', 'yes', 'ypdomainname', 'yuvsplittoppm',
  'yuvtoppm', 'zcat', 'zcmp', 'zdiff', 'zdump', 'zegrep', 'zeisstopnm',
  'zfgrep', 'zforce', 'zgrep', 'zip', 'zipcloak', 'zipgrep', 'zipinfo',
  'zipnote', 'zipsplit', 'zless', 'zmore', 'znew', 'zsoelim']




